--------------------------------------------------------
--  File created - Thursday-December-17-2020   
--------------------------------------------------------
DROP TABLE "APP_INSTITUCIONAL"."TB_BANNER" cascade constraints;
DROP TABLE "APP_INSTITUCIONAL"."TB_CATEGORIA" cascade constraints;
DROP TABLE "APP_INSTITUCIONAL"."TB_LOG_USUARIO_DESATIVADO" cascade constraints;
DROP TABLE "APP_INSTITUCIONAL"."TB_NEWSLETTER" cascade constraints;
DROP TABLE "APP_INSTITUCIONAL"."TB_PERFIL" cascade constraints;
DROP TABLE "APP_INSTITUCIONAL"."TB_POST" cascade constraints;
DROP TABLE "APP_INSTITUCIONAL"."TB_POST_TAG" cascade constraints;
DROP TABLE "APP_INSTITUCIONAL"."TB_REQUISICAO_USUARIO" cascade constraints;
DROP TABLE "APP_INSTITUCIONAL"."TB_TAG" cascade constraints;
DROP TABLE "APP_INSTITUCIONAL"."TB_USUARIO" cascade constraints;
DROP TABLE "APP_INSTITUCIONAL"."TB_USUARIO_PERFIL" cascade constraints;
--------------------------------------------------------
--  DDL for Table TB_BANNER
--------------------------------------------------------

  CREATE TABLE "APP_INSTITUCIONAL"."TB_BANNER" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 151 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TITULO" VARCHAR2(100 BYTE), 
	"SUBTITULO" VARCHAR2(100 BYTE), 
	"DESCRICAO" VARCHAR2(255 BYTE), 
	"DATA_CADASTRO" DATE, 
	"ROTA" VARCHAR2(100 BYTE), 
	"LINK_EXTERNO" CHAR(1 BYTE), 
	"LINK" NVARCHAR2(255), 
	"NOME_LINK" VARCHAR2(100 BYTE), 
	"CAMINHO_DESKTOP" VARCHAR2(255 BYTE), 
	"NOME_IMAGEM_DESKTOP" NVARCHAR2(255), 
	"CAMINHO_MOBILE" VARCHAR2(255 BYTE), 
	"NOME_IMAGEM_MOBILE" VARCHAR2(255 BYTE), 
	"ATIVO" CHAR(1 BYTE), 
	"AREA" VARCHAR2(150 BYTE), 
	"ORDEM" NUMBER(*,0), 
	"TEMPO_EXIBICAO" NUMBER(*,0), 
	"USUARIO_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT" ;
--------------------------------------------------------
--  DDL for Table TB_CATEGORIA
--------------------------------------------------------

  CREATE TABLE "APP_INSTITUCIONAL"."TB_CATEGORIA" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TITULO" VARCHAR2(100 BYTE), 
	"DESCRICAO" VARCHAR2(100 BYTE), 
	"DATA_CADASTRO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT" ;
--------------------------------------------------------
--  DDL for Table TB_LOG_USUARIO_DESATIVADO
--------------------------------------------------------

  CREATE TABLE "APP_INSTITUCIONAL"."TB_LOG_USUARIO_DESATIVADO" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 1000000000000000000000000000 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_REQUISITANTE" NUMBER(10,0), 
	"NOME_USUARIO" VARCHAR2(150 BYTE), 
	"DATA_CADASTRO" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CTSAPP_INSTIT" ;
--------------------------------------------------------
--  DDL for Table TB_NEWSLETTER
--------------------------------------------------------

  CREATE TABLE "APP_INSTITUCIONAL"."TB_NEWSLETTER" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOME_COMPLETO" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"DATA_CADASTRO" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645)
  TABLESPACE "CTSAPP_INSTIT" ;
--------------------------------------------------------
--  DDL for Table TB_PERFIL
--------------------------------------------------------

  CREATE TABLE "APP_INSTITUCIONAL"."TB_PERFIL" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DESCRICAO" VARCHAR2(100 BYTE), 
	"DATA_CADASTRO" DATE, 
	"PRIORIDADE" NUMBER DEFAULT 2
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT" ;
--------------------------------------------------------
--  DDL for Table TB_POST
--------------------------------------------------------

  CREATE TABLE "APP_INSTITUCIONAL"."TB_POST" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TITULO" VARCHAR2(100 BYTE), 
	"SUBTITULO" VARCHAR2(100 BYTE), 
	"DESCRICAO" CLOB, 
	"DESCRICAO_PREVIA" VARCHAR2(255 BYTE), 
	"DATA_CADASTRO" DATE, 
	"DATA_PUBLICACAO" DATE, 
	"DATA_EXPIRACAO" DATE, 
	"CAMINHO_IMAGEM" VARCHAR2(255 BYTE), 
	"NOME_IMAGEM" VARCHAR2(255 BYTE), 
	"DESTAQUE" CHAR(1 BYTE), 
	"ATIVO" CHAR(1 BYTE), 
	"VIZUALIZACOES" NUMBER, 
	"TITULO_PAGINA_SEO" VARCHAR2(150 BYTE), 
	"DESCRICAO_PAGINA_SEO" VARCHAR2(150 BYTE), 
	"SLUG" NVARCHAR2(150), 
	"CATEGORIA_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT" 
 LOB ("DESCRICAO") STORE AS SECUREFILE (
  TABLESPACE "CTSAPP_INSTIT" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TB_POST_TAG
--------------------------------------------------------

  CREATE TABLE "APP_INSTITUCIONAL"."TB_POST_TAG" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"POST_ID" NUMBER, 
	"TAG_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT" ;
--------------------------------------------------------
--  DDL for Table TB_REQUISICAO_USUARIO
--------------------------------------------------------

  CREATE TABLE "APP_INSTITUCIONAL"."TB_REQUISICAO_USUARIO" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOME" VARCHAR2(150 BYTE), 
	"NOME_USUARIO" VARCHAR2(100 BYTE), 
	"TOKEN" VARCHAR2(100 BYTE), 
	"DATA_CADASTRO" DATE, 
	"SUCESSO" CHAR(20 BYTE), 
	"EXPIRADO" CHAR(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT" ;
--------------------------------------------------------
--  DDL for Table TB_TAG
--------------------------------------------------------

  CREATE TABLE "APP_INSTITUCIONAL"."TB_TAG" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DESCRICAO" VARCHAR2(100 BYTE), 
	"DATA_CADASTRO" DATE, 
	"USUARIO_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT" ;
--------------------------------------------------------
--  DDL for Table TB_USUARIO
--------------------------------------------------------

  CREATE TABLE "APP_INSTITUCIONAL"."TB_USUARIO" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOME" VARCHAR2(100 BYTE), 
	"DATA_CADASTRO" DATE, 
	"NOME_USUARIO" VARCHAR2(50 BYTE), 
	"SENHA_HASH" BLOB, 
	"SENHA_SALT" BLOB, 
	"ATIVO" CHAR(1 BYTE) DEFAULT 1, 
	"USUARIO_ROOT" CHAR(1 BYTE) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT" 
 LOB ("SENHA_HASH") STORE AS SECUREFILE (
  TABLESPACE "CTSAPP_INSTIT" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("SENHA_SALT") STORE AS SECUREFILE (
  TABLESPACE "CTSAPP_INSTIT" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TB_USUARIO_PERFIL
--------------------------------------------------------

  CREATE TABLE "APP_INSTITUCIONAL"."TB_USUARIO_PERFIL" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USUARIO_ID" NUMBER(*,0), 
	"PERFIL_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT" ;
--------------------------------------------------------
--  DDL for Index PK_TB_BANNER_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "APP_INSTITUCIONAL"."PK_TB_BANNER_ID" ON "APP_INSTITUCIONAL"."TB_BANNER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT" ;
--------------------------------------------------------
--  DDL for Index PK_TB_CATEGORIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "APP_INSTITUCIONAL"."PK_TB_CATEGORIA" ON "APP_INSTITUCIONAL"."TB_CATEGORIA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT" ;
--------------------------------------------------------
--  DDL for Index PK_TB_LOG_USUARIO_DESATIVADO_I
--------------------------------------------------------

  CREATE UNIQUE INDEX "APP_INSTITUCIONAL"."PK_TB_LOG_USUARIO_DESATIVADO_I" ON "APP_INSTITUCIONAL"."TB_LOG_USUARIO_DESATIVADO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CTSAPP_INSTIT" ;
--------------------------------------------------------
--  DDL for Index PK_TB_NEWSLETTER
--------------------------------------------------------

  CREATE UNIQUE INDEX "APP_INSTITUCIONAL"."PK_TB_NEWSLETTER" ON "APP_INSTITUCIONAL"."TB_NEWSLETTER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CTSAPP_INSTIT" ;
--------------------------------------------------------
--  DDL for Index PK_TB_PERFIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "APP_INSTITUCIONAL"."PK_TB_PERFIL" ON "APP_INSTITUCIONAL"."TB_PERFIL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT" ;
--------------------------------------------------------
--  DDL for Index PK_TB_POST
--------------------------------------------------------

  CREATE UNIQUE INDEX "APP_INSTITUCIONAL"."PK_TB_POST" ON "APP_INSTITUCIONAL"."TB_POST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT" ;
--------------------------------------------------------
--  DDL for Index PK_TB_POST_TAG
--------------------------------------------------------

  CREATE UNIQUE INDEX "APP_INSTITUCIONAL"."PK_TB_POST_TAG" ON "APP_INSTITUCIONAL"."TB_POST_TAG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT" ;
--------------------------------------------------------
--  DDL for Index PK_TB_REQUISIAO_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "APP_INSTITUCIONAL"."PK_TB_REQUISIAO_USUARIO" ON "APP_INSTITUCIONAL"."TB_REQUISICAO_USUARIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT" ;
--------------------------------------------------------
--  DDL for Index PK_TB_TAG
--------------------------------------------------------

  CREATE UNIQUE INDEX "APP_INSTITUCIONAL"."PK_TB_TAG" ON "APP_INSTITUCIONAL"."TB_TAG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT" ;
--------------------------------------------------------
--  DDL for Index PK_TB_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "APP_INSTITUCIONAL"."PK_TB_USUARIO" ON "APP_INSTITUCIONAL"."TB_USUARIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT" ;
--------------------------------------------------------
--  DDL for Index PK_TB_USUARIO_PERFIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "APP_INSTITUCIONAL"."PK_TB_USUARIO_PERFIL" ON "APP_INSTITUCIONAL"."TB_USUARIO_PERFIL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT" ;
--------------------------------------------------------
--  Constraints for Table TB_BANNER
--------------------------------------------------------

  ALTER TABLE "APP_INSTITUCIONAL"."TB_BANNER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_BANNER" MODIFY ("TITULO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_BANNER" MODIFY ("DATA_CADASTRO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_BANNER" MODIFY ("ROTA" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_BANNER" MODIFY ("LINK_EXTERNO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_BANNER" MODIFY ("CAMINHO_DESKTOP" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_BANNER" MODIFY ("CAMINHO_MOBILE" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_BANNER" MODIFY ("ATIVO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_BANNER" MODIFY ("AREA" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_BANNER" MODIFY ("USUARIO_ID" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_BANNER" ADD CONSTRAINT "CK_TB_BANNER_ATIVO" CHECK (ATIVO IN ('1', '0')) ENABLE;
  ALTER TABLE "APP_INSTITUCIONAL"."TB_BANNER" ADD CONSTRAINT "CK_TB_BANNER_LINK_EXTERNO" CHECK (LINK_EXTERNO IN ('1', '0')) ENABLE;
  ALTER TABLE "APP_INSTITUCIONAL"."TB_BANNER" ADD CONSTRAINT "PK_TB_BANNER_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_LOG_USUARIO_DESATIVADO
--------------------------------------------------------

  ALTER TABLE "APP_INSTITUCIONAL"."TB_LOG_USUARIO_DESATIVADO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_LOG_USUARIO_DESATIVADO" MODIFY ("ID_REQUISITANTE" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_LOG_USUARIO_DESATIVADO" MODIFY ("NOME_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_LOG_USUARIO_DESATIVADO" MODIFY ("DATA_CADASTRO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_LOG_USUARIO_DESATIVADO" ADD CONSTRAINT "PK_TB_LOG_USUARIO_DESATIVADO_I" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CTSAPP_INSTIT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_USUARIO_PERFIL
--------------------------------------------------------

  ALTER TABLE "APP_INSTITUCIONAL"."TB_USUARIO_PERFIL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_USUARIO_PERFIL" MODIFY ("USUARIO_ID" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_USUARIO_PERFIL" MODIFY ("PERFIL_ID" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_USUARIO_PERFIL" ADD CONSTRAINT "PK_TB_USUARIO_PERFIL" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_CATEGORIA
--------------------------------------------------------

  ALTER TABLE "APP_INSTITUCIONAL"."TB_CATEGORIA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_CATEGORIA" MODIFY ("TITULO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_CATEGORIA" MODIFY ("DESCRICAO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_CATEGORIA" MODIFY ("DATA_CADASTRO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_CATEGORIA" ADD CONSTRAINT "PK_TB_CATEGORIA" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_REQUISICAO_USUARIO
--------------------------------------------------------

  ALTER TABLE "APP_INSTITUCIONAL"."TB_REQUISICAO_USUARIO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_REQUISICAO_USUARIO" MODIFY ("NOME_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_REQUISICAO_USUARIO" MODIFY ("TOKEN" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_REQUISICAO_USUARIO" MODIFY ("DATA_CADASTRO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_REQUISICAO_USUARIO" MODIFY ("SUCESSO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_REQUISICAO_USUARIO" MODIFY ("EXPIRADO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_REQUISICAO_USUARIO" ADD CONSTRAINT "PK_TB_REQUISICAO_USUARIO" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "APP_INSTITUCIONAL"."PK_TB_REQUISIAO_USUARIO" ON "APP_INSTITUCIONAL"."TB_REQUISICAO_USUARIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_TAG
--------------------------------------------------------

  ALTER TABLE "APP_INSTITUCIONAL"."TB_TAG" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_TAG" MODIFY ("DESCRICAO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_TAG" MODIFY ("DATA_CADASTRO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_TAG" MODIFY ("USUARIO_ID" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_TAG" ADD CONSTRAINT "PK_TB_TAG" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_USUARIO
--------------------------------------------------------

  ALTER TABLE "APP_INSTITUCIONAL"."TB_USUARIO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_USUARIO" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_USUARIO" MODIFY ("DATA_CADASTRO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_USUARIO" MODIFY ("ATIVO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_USUARIO" ADD CONSTRAINT "PK_TB_USUARIO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT"  ENABLE;
  ALTER TABLE "APP_INSTITUCIONAL"."TB_USUARIO" MODIFY ("NOME_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_USUARIO" MODIFY ("USUARIO_ROOT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_POST
--------------------------------------------------------

  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST" MODIFY ("TITULO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST" MODIFY ("DATA_CADASTRO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST" MODIFY ("DATA_PUBLICACAO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST" MODIFY ("DESTAQUE" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST" MODIFY ("VIZUALIZACOES" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST" MODIFY ("TITULO_PAGINA_SEO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST" MODIFY ("DESCRICAO_PAGINA_SEO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST" MODIFY ("CATEGORIA_ID" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST" ADD CONSTRAINT "PK_TB_POST" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT"  ENABLE;
  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST" ADD UNIQUE ("SLUG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_PERFIL
--------------------------------------------------------

  ALTER TABLE "APP_INSTITUCIONAL"."TB_PERFIL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_PERFIL" MODIFY ("DESCRICAO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_PERFIL" MODIFY ("DATA_CADASTRO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_PERFIL" MODIFY ("PRIORIDADE" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_PERFIL" ADD CONSTRAINT "PK_TB_PERFIL" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_POST_TAG
--------------------------------------------------------

  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST_TAG" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST_TAG" MODIFY ("POST_ID" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST_TAG" MODIFY ("TAG_ID" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST_TAG" ADD CONSTRAINT "PK_TB_POST_TAG" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_NEWSLETTER
--------------------------------------------------------

  ALTER TABLE "APP_INSTITUCIONAL"."TB_NEWSLETTER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_NEWSLETTER" MODIFY ("NOME_COMPLETO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_NEWSLETTER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_NEWSLETTER" MODIFY ("DATA_CADASTRO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_NEWSLETTER" ADD CONSTRAINT "PK_TB_NEWSLETTER" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CTSAPP_INSTIT"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_BANNER
--------------------------------------------------------

  ALTER TABLE "APP_INSTITUCIONAL"."TB_BANNER" ADD CONSTRAINT "FK_TB_BANNER_USUARIO_ID" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "APP_INSTITUCIONAL"."TB_USUARIO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_POST
--------------------------------------------------------

  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST" ADD CONSTRAINT "TB_CATEGORIA_TB_POST_FK" FOREIGN KEY ("CATEGORIA_ID")
	  REFERENCES "APP_INSTITUCIONAL"."TB_CATEGORIA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_POST_TAG
--------------------------------------------------------

  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST_TAG" ADD CONSTRAINT "TB_POST_TB_POST_TAG_FK" FOREIGN KEY ("POST_ID")
	  REFERENCES "APP_INSTITUCIONAL"."TB_POST" ("ID") ENABLE;
  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST_TAG" ADD CONSTRAINT "TB_TAG_TB_POST_TAG_FK" FOREIGN KEY ("TAG_ID")
	  REFERENCES "APP_INSTITUCIONAL"."TB_TAG" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_TAG
--------------------------------------------------------

  ALTER TABLE "APP_INSTITUCIONAL"."TB_TAG" ADD CONSTRAINT "TB_USUARIO_TB_TAG_FK" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "APP_INSTITUCIONAL"."TB_USUARIO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_USUARIO_PERFIL
--------------------------------------------------------

  ALTER TABLE "APP_INSTITUCIONAL"."TB_USUARIO_PERFIL" ADD CONSTRAINT "FK_TB_USUARIO_PERFIL_PERFIL_ID" FOREIGN KEY ("PERFIL_ID")
	  REFERENCES "APP_INSTITUCIONAL"."TB_PERFIL" ("ID") ENABLE;
  ALTER TABLE "APP_INSTITUCIONAL"."TB_USUARIO_PERFIL" ADD CONSTRAINT "FK_TB_USUARIO_PERFIL_USUARIO_ID" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "APP_INSTITUCIONAL"."TB_USUARIO" ("ID") ENABLE;
