--------------------------------------------------------
--  Arquivo criado - Sexta-feira-Fevereiro-26-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TB_BANNER
--------------------------------------------------------

  CREATE TABLE "APP_INSTITUCIONAL"."TB_BANNER" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 151 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TITULO" VARCHAR2(100 BYTE), 
	"SUBTITULO" VARCHAR2(100 BYTE), 
	"DESCRICAO" VARCHAR2(255 BYTE), 
	"DATA_CADASTRO" DATE, 
	"ROTA" VARCHAR2(100 BYTE), 
	"LINK_EXTERNO" CHAR(1 BYTE), 
	"LINK" NVARCHAR2(255), 
	"NOME_LINK" VARCHAR2(100 BYTE), 
	"CAMINHO_DESKTOP" VARCHAR2(255 BYTE), 
	"NOME_IMAGEM_DESKTOP" NVARCHAR2(255), 
	"CAMINHO_MOBILE" VARCHAR2(255 BYTE), 
	"NOME_IMAGEM_MOBILE" VARCHAR2(255 BYTE), 
	"ATIVO" CHAR(1 BYTE), 
	"AREA" VARCHAR2(150 BYTE), 
	"ORDEM" NUMBER(*,0), 
	"TEMPO_EXIBICAO" NUMBER(*,0), 
	"USUARIO_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT" ;
--------------------------------------------------------
--  DDL for Index PK_TB_BANNER_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "APP_INSTITUCIONAL"."PK_TB_BANNER_ID" ON "APP_INSTITUCIONAL"."TB_BANNER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT" ;
--------------------------------------------------------
--  Constraints for Table TB_BANNER
--------------------------------------------------------

  ALTER TABLE "APP_INSTITUCIONAL"."TB_BANNER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_BANNER" MODIFY ("TITULO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_BANNER" MODIFY ("DATA_CADASTRO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_BANNER" MODIFY ("ROTA" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_BANNER" MODIFY ("LINK_EXTERNO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_BANNER" MODIFY ("CAMINHO_DESKTOP" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_BANNER" MODIFY ("CAMINHO_MOBILE" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_BANNER" MODIFY ("ATIVO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_BANNER" MODIFY ("AREA" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_BANNER" MODIFY ("USUARIO_ID" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_BANNER" ADD CONSTRAINT "CK_TB_BANNER_ATIVO" CHECK (ATIVO IN ('1', '0')) ENABLE;
  ALTER TABLE "APP_INSTITUCIONAL"."TB_BANNER" ADD CONSTRAINT "CK_TB_BANNER_LINK_EXTERNO" CHECK (LINK_EXTERNO IN ('1', '0')) ENABLE;
  ALTER TABLE "APP_INSTITUCIONAL"."TB_BANNER" ADD CONSTRAINT "PK_TB_BANNER_ID" PRIMARY KEY ("ID")
  USING INDEX "APP_INSTITUCIONAL"."PK_TB_BANNER_ID"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_BANNER
--------------------------------------------------------

  ALTER TABLE "APP_INSTITUCIONAL"."TB_BANNER" ADD CONSTRAINT "FK_TB_BANNER_USUARIO_ID" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "APP_INSTITUCIONAL"."TB_USUARIO" ("ID") ENABLE;
