--------------------------------------------------------
--  Arquivo criado - Sexta-feira-Fevereiro-26-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TB_LOG_USUARIO_DESATIVADO
--------------------------------------------------------

  CREATE TABLE "APP_INSTITUCIONAL"."TB_LOG_USUARIO_DESATIVADO" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 1000000000000000000000000000 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_REQUISITANTE" NUMBER(10,0), 
	"NOME_USUARIO" VARCHAR2(150 BYTE), 
	"DATA_CADASTRO" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CTSAPP_INSTIT" ;
--------------------------------------------------------
--  DDL for Index PK_TB_LOG_USUARIO_DESATIVADO_I
--------------------------------------------------------

  CREATE UNIQUE INDEX "APP_INSTITUCIONAL"."PK_TB_LOG_USUARIO_DESATIVADO_I" ON "APP_INSTITUCIONAL"."TB_LOG_USUARIO_DESATIVADO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "CTSAPP_INSTIT" ;
--------------------------------------------------------
--  Constraints for Table TB_LOG_USUARIO_DESATIVADO
--------------------------------------------------------

  ALTER TABLE "APP_INSTITUCIONAL"."TB_LOG_USUARIO_DESATIVADO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_LOG_USUARIO_DESATIVADO" MODIFY ("ID_REQUISITANTE" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_LOG_USUARIO_DESATIVADO" MODIFY ("NOME_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_LOG_USUARIO_DESATIVADO" MODIFY ("DATA_CADASTRO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_LOG_USUARIO_DESATIVADO" ADD CONSTRAINT "PK_TB_LOG_USUARIO_DESATIVADO_I" PRIMARY KEY ("ID")
  USING INDEX "APP_INSTITUCIONAL"."PK_TB_LOG_USUARIO_DESATIVADO_I"  ENABLE;
