--------------------------------------------------------
--  Arquivo criado - Sexta-feira-Fevereiro-26-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TB_POST
--------------------------------------------------------

  CREATE TABLE "APP_INSTITUCIONAL"."TB_POST" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TITULO" VARCHAR2(100 BYTE), 
	"SUBTITULO" VARCHAR2(100 BYTE), 
	"DESCRICAO" CLOB, 
	"DESCRICAO_PREVIA" VARCHAR2(255 BYTE), 
	"DATA_CADASTRO" DATE, 
	"DATA_PUBLICACAO" DATE, 
	"DATA_EXPIRACAO" DATE, 
	"CAMINHO_IMAGEM" VARCHAR2(255 BYTE), 
	"NOME_IMAGEM" VARCHAR2(255 BYTE), 
	"DESTAQUE" CHAR(1 BYTE), 
	"ATIVO" CHAR(1 BYTE), 
	"VIZUALIZACOES" NUMBER, 
	"TITULO_PAGINA_SEO" VARCHAR2(150 BYTE), 
	"DESCRICAO_PAGINA_SEO" VARCHAR2(150 BYTE), 
	"SLUG" NVARCHAR2(150), 
	"CATEGORIA_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT" 
 LOB ("DESCRICAO") STORE AS SECUREFILE (
  TABLESPACE "CTSAPP_INSTIT" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index PK_TB_POST
--------------------------------------------------------

  CREATE UNIQUE INDEX "APP_INSTITUCIONAL"."PK_TB_POST" ON "APP_INSTITUCIONAL"."TB_POST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT" ;
--------------------------------------------------------
--  DDL for Index SYS_C0091362
--------------------------------------------------------

  CREATE UNIQUE INDEX "APP_INSTITUCIONAL"."SYS_C0091362" ON "APP_INSTITUCIONAL"."TB_POST" ("SLUG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT" ;
--------------------------------------------------------
--  Constraints for Table TB_POST
--------------------------------------------------------

  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST" MODIFY ("TITULO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST" MODIFY ("DATA_CADASTRO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST" MODIFY ("DATA_PUBLICACAO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST" MODIFY ("DESTAQUE" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST" MODIFY ("VIZUALIZACOES" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST" MODIFY ("TITULO_PAGINA_SEO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST" MODIFY ("DESCRICAO_PAGINA_SEO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST" MODIFY ("CATEGORIA_ID" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST" ADD CONSTRAINT "PK_TB_POST" PRIMARY KEY ("ID")
  USING INDEX "APP_INSTITUCIONAL"."PK_TB_POST"  ENABLE;
  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST" ADD UNIQUE ("SLUG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_POST
--------------------------------------------------------

  ALTER TABLE "APP_INSTITUCIONAL"."TB_POST" ADD CONSTRAINT "TB_CATEGORIA_TB_POST_FK" FOREIGN KEY ("CATEGORIA_ID")
	  REFERENCES "APP_INSTITUCIONAL"."TB_CATEGORIA" ("ID") ENABLE;
