--------------------------------------------------------
--  Arquivo criado - Sexta-feira-Fevereiro-26-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TB_TAG
--------------------------------------------------------

  CREATE TABLE "APP_INSTITUCIONAL"."TB_TAG" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DESCRICAO" VARCHAR2(100 BYTE), 
	"DATA_CADASTRO" DATE, 
	"USUARIO_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT" ;
--------------------------------------------------------
--  DDL for Index PK_TB_TAG
--------------------------------------------------------

  CREATE UNIQUE INDEX "APP_INSTITUCIONAL"."PK_TB_TAG" ON "APP_INSTITUCIONAL"."TB_TAG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CTSAPP_INSTIT" ;
--------------------------------------------------------
--  Constraints for Table TB_TAG
--------------------------------------------------------

  ALTER TABLE "APP_INSTITUCIONAL"."TB_TAG" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_TAG" MODIFY ("DESCRICAO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_TAG" MODIFY ("DATA_CADASTRO" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_TAG" MODIFY ("USUARIO_ID" NOT NULL ENABLE);
  ALTER TABLE "APP_INSTITUCIONAL"."TB_TAG" ADD CONSTRAINT "PK_TB_TAG" PRIMARY KEY ("ID")
  USING INDEX "APP_INSTITUCIONAL"."PK_TB_TAG"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_TAG
--------------------------------------------------------

  ALTER TABLE "APP_INSTITUCIONAL"."TB_TAG" ADD CONSTRAINT "TB_USUARIO_TB_TAG_FK" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "APP_INSTITUCIONAL"."TB_USUARIO" ("ID") ENABLE;
