--------------------------------------------------------
--  Arquivo criado - Sexta-feira-Fevereiro-26-2021   
--------------------------------------------------------
REM INSERTING into APP_INSTITUCIONAL.TB_TAG
SET DEFINE OFF;
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('44','sedentarismo',to_date('25/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('51','exercícios',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('52','trabalhos',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('60','alimentação',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('45','treino mais eficiente',to_date('25/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('46','ansiedade',to_date('25/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('61','exercício físico',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('62','suplemento',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('63','suplementos alimentares',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('64','vitaminas',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('65','dancar',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('66','hobbies',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('67','ouvir um som',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('68','devagar',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('69','dieta',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('70','emagrecer',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('76','criança',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('77','obesidade',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('80','colaboradores',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('81','plano de saúde empresarial',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('82','retenção de talentos',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('83','sinistralidade',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('84','convênio médico empresarial',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('85','taxa de sinistralidade',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('86','sem açúcar',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('87','pratinho saudável',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('97','risco em saúde',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('111','adolescência',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('115','materno',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('113','copa',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('114','leite',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('116','nutrição infantil',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('117','frança',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('118','turismo',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('119','rússia',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('120','seguro viagem',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('121','travel',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('122','assistência',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('123','dia da mulher',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('124','igualdade',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('125','leite materno',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('126','controlar os gastos',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('127','instruir',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('128','inflação médica',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('129','anemia',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('130','ferro',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('143','desordem alimentar',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('144','cigarro eletronico faz mal',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('145','doenças de inverno',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('146','síndrome metabólica',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('272','adolescentes',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('158','Síndrome de Burnout',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('170','febre amarela',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('177','depressão na gravidez',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('185','alergias',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('186','vacinas para crianças',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('195','gestação',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('196','gravidez',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('200','assistencia medica',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('201','dores',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('202','google',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('203','duvidas',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('204','gripe',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('205','H3N2',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('206','vacina',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('207','vacina de gripe',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('208','poluição',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('209','prevenção',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('210','qualidade de vida',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('211','rinite',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('212','saúde respitatoria',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('249','alimentos',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('250','cuidados',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('251','hepatite',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('252','diabetes',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('273','herbiatria',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('73','sono',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('8','care plus',to_date('09/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('9','plano de saúde',to_date('09/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('53','viagem',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('54','bodyweight',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('74','esportes',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('75','nutrição',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('78','dicas para rh',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('79','retenção de talentos',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('96','saúde emocional',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('149','meditação',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('150','meditar',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('151','mindful eating',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('152','mindfulness',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('168','doenças cronicas não transmissiveis',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('169','conjuntivite',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('172','cancer infantil',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('173','vida em movimento',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('190','infecção',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('191','sepse',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('192','infarto',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('197','cigarro',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('198','parar de fumar',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('199','qualidade de vida',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('245','bem-estar',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('246','hortoterapia',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('247','natureza',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('253','cancer',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('254','mulher',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('255','saude',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('256','asma',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('264','toxoplasmose',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('262','chocolate',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('263','vicio',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('279','vacinação',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('56','barriga',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('57','emagrecimento',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('55','alimentação',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('58','gordura abdominal',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('59','metabolismo',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('98','valor nutricional',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('99','low carb',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('100','saudável',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('101','masterchef',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('102','autismo',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('103','saúde',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('104','master international',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('105','institucional',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('106','prêmios',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('107','saúde do homem',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('108','doação de órgãos',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('109','croácia',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('110','ganhar peso',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('148','saude intestinal',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('153','síndrome do panico',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('154','calor',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('155','tecnologia em saúde',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('174','bebê',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('175','criança',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('176','exames',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('187','estresse',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('188','saúde mental',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('189','doação de sangue',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('213','bafo',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('214','halito',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('215','halitose',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('239','amor',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('240','direitos',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('241','lgbt',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('243','colesterol',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('244','ldl',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('248','tecnologia',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('257','sentado',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('258','jovens',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('259','pressão alta',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('41','começar a correr',to_date('25/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('42','lesão no joelho',to_date('25/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('43','atividade física',to_date('25/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('47','ioga',to_date('25/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('48','saúde do coração',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('49','dança',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('181','alzheimer',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('147','ter mais energia',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('182','demencia',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('183','memoria',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('184','idosos',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('223','depressão',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('224','suicidio',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('225','alerta',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('226','cvv',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('227','humor',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('242','fumar',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('265','velhos habitos',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('268','pressão',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('269','rins',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('270','estudo',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('271','musica',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('88','ervas e especiarias',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('23','aumentar os músculos',to_date('12/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('71','obeso',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('72','profissional',to_date('27/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('89','dicas',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('90','infográfico',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('91','óleo de coco',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('92','dieta vegana',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('93','alimentação infantil',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('94','fim de ano',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('95','amamentação',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('131','bichectomia',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('132','cancer de mama',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('133','catarata',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('134','cegueira',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('135','chip de beleza',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('136','glaucoma',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('137','hormônios',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('138','menstruação',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('139','olhos',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('140','retina',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('141','visão',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('142','TPM',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('156','clinico geral',to_date('28/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('171','telemedicina',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('178','saúde bucal',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('179','nascimento',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('180','parto',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('193','fake nws',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('194','Ministerio da Saude',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('216','cancer de pele',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('217','protetor solar',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('274','pancreas',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('219','proteção solar',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('220','dormir',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('221','oms',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('222','sono',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('228','excessos',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('236','obito',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('230','perigo',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('231','tabaco',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('232','insonia',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('233','qualidade',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('234','sono',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('235','hipertensão',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('237','beneficios ',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('238','viagem tranquila',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('266','automedicação',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('267','mulheres hormonios',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('275','tratamentos',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('276','bons habitos',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('277','fertilidade',to_date('30/11/20','DD/MM/RR'),'1');
Insert into APP_INSTITUCIONAL.TB_TAG (ID,DESCRICAO,DATA_CADASTRO,USUARIO_ID) values ('278','filhos',to_date('30/11/20','DD/MM/RR'),'1');
commit;